### ISSUE TITLE
I am having trouble with the setup

### ISSUE THREAD

**Issue by zoderiffic** [suoto/vim-hdl#36]
I get the following error

```
"vimhdl.vim" 201L, 7227C
Error detected while processing function vimhdl#setup..<SNR>44_setupPython:
line   32:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
AttributeError: 'module' object has no attribute 'NullHandler'
```

**Comment by suoto** [comment]
Could you please try running the following within Vim?
```:py import logging; print(logging.__version__); print(logging.NullHandler)```
or (if you have Python 3.x)
```:py3 import logging; print(logging.__version__); print(logging.NullHandler)```

**Comment by zoderiffic** [comment]
The py3 went through,.

just the py  i get the following error,

I am quite new at all this so I might be really wrong at every single point



```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'NullHandler'

```

**Comment by zoderiffic** [comment]
Also was I supposed to get some feedback from any of those two commands other than a blank return?

**Comment by suoto** [comment]
If any of the commands worked, it should be fine. For some reason it seems your Python 2.x environment is missing the logging library, but this should be installed by default. Maybe try running
```
pip install logging
```
and restart Vim afterwards.

**Comment by suoto** [comment]
Closed due to inactivity. Please let me know if the issue persists.
