### ISSUE TITLE
Cannot call python3 executable by default in Windows

### ISSUE THREAD

**Issue by roastduck** [suoto/vim-hdl#39]
The official distribution of Python 3 for Windows has the executable name `python` instead of `python3`. Normally vim can work with it, and `echo has("python3")` returns 1. But it will cause a `FileNotFoundError` in this plugin. Changing the executable of Python to `python3` can solve this problem.

**Comment by suoto** [comment]
This plugin is being deprecated in favor of [hdl_checker](https://github.com/suoto/hdl_checker), which supports Windows as long as your editor uses a [LSP client](https://microsoft.github.io/language-server-protocol/implementors/tools/)
